export default {
  LOAD_COMPANY_DATA_SUCCESS: 'LOAD_COMPANY_DATA_SUCCESS',
  LOAD_CONTACT_DATA_SUCCESS: 'LOAD_CONTACT_DATA_SUCCESS',
  DELETE_CARD: 'DELETE_CARD',
  UPDATE_CONTACT: 'UPDATE_CONTACT',
  UPDATE_COMPANY: 'UPDATE_COMPANY',
  ADD_PHOTO: 'ADD_PHOTO',
  DELETE_PHOTO: 'DELETE_PHOTO',
};
